//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayAPI.BankService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankService.IBankService")]
    public interface IBankService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/CreateBank", ReplyAction="http://tempuri.org/IBankService/CreateBankResponse")]
        PayAPI.BankService.CreateBankResponse CreateBank(PayAPI.BankService.CreateBankRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/CreateBank", ReplyAction="http://tempuri.org/IBankService/CreateBankResponse")]
        System.Threading.Tasks.Task<PayAPI.BankService.CreateBankResponse> CreateBankAsync(PayAPI.BankService.CreateBankRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetAllBanks", ReplyAction="http://tempuri.org/IBankService/GetAllBanksResponse")]
        PayAPI.BankService.GetAllBanksResponse GetAllBanks(PayAPI.BankService.GetAllBanksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetAllBanks", ReplyAction="http://tempuri.org/IBankService/GetAllBanksResponse")]
        System.Threading.Tasks.Task<PayAPI.BankService.GetAllBanksResponse> GetAllBanksAsync(PayAPI.BankService.GetAllBanksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetBankById", ReplyAction="http://tempuri.org/IBankService/GetBankByIdResponse")]
        PayAPI.BankService.GetBankByIdResponse GetBankById(PayAPI.BankService.GetBankByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetBankById", ReplyAction="http://tempuri.org/IBankService/GetBankByIdResponse")]
        System.Threading.Tasks.Task<PayAPI.BankService.GetBankByIdResponse> GetBankByIdAsync(PayAPI.BankService.GetBankByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetBankByCode", ReplyAction="http://tempuri.org/IBankService/GetBankByCodeResponse")]
        PayAPI.BankService.GetBankByCodeResponse GetBankByCode(PayAPI.BankService.GetBankByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetBankByCode", ReplyAction="http://tempuri.org/IBankService/GetBankByCodeResponse")]
        System.Threading.Tasks.Task<PayAPI.BankService.GetBankByCodeResponse> GetBankByCodeAsync(PayAPI.BankService.GetBankByCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateBank", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateBankRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string bankName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string bankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string bankId;
        
        public CreateBankRequest() {
        }
        
        public CreateBankRequest(string bankName, string bankCode, string bankId) {
            this.bankName = bankName;
            this.bankCode = bankCode;
            this.bankId = bankId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateBankResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateBankResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PayService.DataContract.ServiceResponse<bool> CreateBankResult;
        
        public CreateBankResponse() {
        }
        
        public CreateBankResponse(PayService.DataContract.ServiceResponse<bool> CreateBankResult) {
            this.CreateBankResult = CreateBankResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllBanks", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllBanksRequest {
        
        public GetAllBanksRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllBanksResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllBanksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PayService.DataContract.ServiceResponse<System.Collections.Generic.List<PayService.DataContract.BankDTO>> GetAllBanksResult;
        
        public GetAllBanksResponse() {
        }
        
        public GetAllBanksResponse(PayService.DataContract.ServiceResponse<System.Collections.Generic.List<PayService.DataContract.BankDTO>> GetAllBanksResult) {
            this.GetAllBanksResult = GetAllBanksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBankById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBankByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string bankId;
        
        public GetBankByIdRequest() {
        }
        
        public GetBankByIdRequest(string bankId) {
            this.bankId = bankId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBankByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBankByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PayService.DataContract.ServiceResponse<PayService.DataContract.BankDTO> GetBankByIdResult;
        
        public GetBankByIdResponse() {
        }
        
        public GetBankByIdResponse(PayService.DataContract.ServiceResponse<PayService.DataContract.BankDTO> GetBankByIdResult) {
            this.GetBankByIdResult = GetBankByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBankByCode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBankByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string code;
        
        public GetBankByCodeRequest() {
        }
        
        public GetBankByCodeRequest(string code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBankByCodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBankByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PayService.DataContract.ServiceResponse<PayService.DataContract.BankDTO> GetBankByCodeResult;
        
        public GetBankByCodeResponse() {
        }
        
        public GetBankByCodeResponse(PayService.DataContract.ServiceResponse<PayService.DataContract.BankDTO> GetBankByCodeResult) {
            this.GetBankByCodeResult = GetBankByCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankServiceChannel : PayAPI.BankService.IBankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<PayAPI.BankService.IBankService>, PayAPI.BankService.IBankService {
        
        public BankServiceClient() {
        }
        
        public BankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PayAPI.BankService.CreateBankResponse CreateBank(PayAPI.BankService.CreateBankRequest request) {
            return base.Channel.CreateBank(request);
        }
        
        public System.Threading.Tasks.Task<PayAPI.BankService.CreateBankResponse> CreateBankAsync(PayAPI.BankService.CreateBankRequest request) {
            return base.Channel.CreateBankAsync(request);
        }
        
        public PayAPI.BankService.GetAllBanksResponse GetAllBanks(PayAPI.BankService.GetAllBanksRequest request) {
            return base.Channel.GetAllBanks(request);
        }
        
        public System.Threading.Tasks.Task<PayAPI.BankService.GetAllBanksResponse> GetAllBanksAsync(PayAPI.BankService.GetAllBanksRequest request) {
            return base.Channel.GetAllBanksAsync(request);
        }
        
        public PayAPI.BankService.GetBankByIdResponse GetBankById(PayAPI.BankService.GetBankByIdRequest request) {
            return base.Channel.GetBankById(request);
        }
        
        public System.Threading.Tasks.Task<PayAPI.BankService.GetBankByIdResponse> GetBankByIdAsync(PayAPI.BankService.GetBankByIdRequest request) {
            return base.Channel.GetBankByIdAsync(request);
        }
        
        public PayAPI.BankService.GetBankByCodeResponse GetBankByCode(PayAPI.BankService.GetBankByCodeRequest request) {
            return base.Channel.GetBankByCode(request);
        }
        
        public System.Threading.Tasks.Task<PayAPI.BankService.GetBankByCodeResponse> GetBankByCodeAsync(PayAPI.BankService.GetBankByCodeRequest request) {
            return base.Channel.GetBankByCodeAsync(request);
        }
    }
}
