//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.DAL.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SplitPayment
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string PaymentCode { get; set; }
        public Nullable<float> Amount { get; set; }
        public Nullable<int> PayId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> AccId { get; set; }
    
        public virtual AccountDetail AccountDetail { get; set; }
        public virtual PaymentDetail Payment { get; set; }
    }
}
