//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.DAL.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public Nullable<bool> IsVisibletoAdmin { get; set; }
        public Nullable<bool> IsVisibleToUser { get; set; }
        public Nullable<long> PeriodId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string TransactionAmount { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseDescription { get; set; }
        public Nullable<System.DateTime> UpdateEntry { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string PostedBy { get; set; }
        public string TransactionRefNo { get; set; }
        public string MerchantRef { get; set; }
        public string BankRef { get; set; }
    
        public virtual DayPeriod DayPeriod { get; set; }
        public virtual PaymentInvoice PaymentInvoice { get; set; }
    }
}
