//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Payment.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthPeriod : Period
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonthPeriod()
        {
            this.DayPeriods = new HashSet<DayPeriod>();
        }
    
        public Nullable<long> YrId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DayPeriod> DayPeriods { get; set; }
        public virtual FiscalPeriod FiscalPeriod { get; set; }
    }
}
