//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Payment.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Payment_DEVEntities : DbContext
    {
        public Payment_DEVEntities()
            : base("name=Payment_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountDetail> AccountDetails { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Payer> Payers { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentEngine> PaymentEngines { get; set; }
        public virtual DbSet<PaymentInvoice> PaymentInvoices { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SplitPayment> SplitPayments { get; set; }
        public virtual DbSet<TransactionLog> TransactionLogs { get; set; }
    }
}
