//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Payment.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentInvoice()
        {
            this.TransactionLogs = new HashSet<TransactionLog>();
        }
    
        public long Id { get; set; }
        public Nullable<long> PayerId { get; set; }
        public Nullable<int> PayId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string PostedBy { get; set; }
        public string RevenueCode { get; set; }
    
        public virtual Payer Payer { get; set; }
        public virtual Payment Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLog> TransactionLogs { get; set; }
    }
}
