//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Payment.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Payment1 = new HashSet<Payment>();
            this.PaymentInvoices = new HashSet<PaymentInvoice>();
            this.SplitPayments = new HashSet<SplitPayment>();
        }
    
        public int Id { get; set; }
        public string PaymentDescription { get; set; }
        public string PaymentCode { get; set; }
        public Nullable<float> TotalAmount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> SchId { get; set; }
        public Nullable<int> PayEngineId { get; set; }
        public Nullable<int> ReqId { get; set; }
        public Nullable<long> PeriodId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment1 { get; set; }
        public virtual Payment Payment2 { get; set; }
        public virtual PaymentEngine PaymentEngine { get; set; }
        public virtual Period Period { get; set; }
        public virtual School School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentInvoice> PaymentInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SplitPayment> SplitPayments { get; set; }
    }
}
